### ISSUE TITLE
Bundle any of: `sudo` (and `google-chome-stable`, `chromedriver`)

### ISSUE THREAD

**Issue by marcandre** [erlef/docker-elixir#26]
First, thank you so much for maintaining the elixir images ❤️ 

Trying to install `chromedriver` turned out to be way more complicated than I was hoping for. I'm a n00b, so it [took help](https://github.com/nanasess/setup-chromedriver/issues/32)  and a few hours of my time.

The formula I was using required `sudo` (not installed), and `google-chrome`, also not installed.

I'm a n00b in these kinds of things, but please consider bundling at least`sudo` (for standard and alpine) and ideally `google-chome-stable` and `chromedriver` (maybe just for alpine?)

This is using the non-`slim` version. My quest was even more complicated because it took a while to realize I was using the `-slim` version, so was also missing `wget`, `curl`, `unzip`, `gnupg`. Some documentation about the `slim` vs `alpine` vs "standard" version would be welcome.

Let me know if (and how) I can help.

FWIW, here's what I ended up using in my github action:

```yaml
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        apt-get update && apt-get install -y sudo google-chrome-stable
    - name: Install chromedriver
      uses: nanasess/setup-chromedriver@master
```
